version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    # - location: scripts/after_install.sh
    - location: scripts/kill_containers.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root